### ISSUE TITLE
Testing poll plugin

### ISSUE THREAD

**Issue by dylanatsmith** [email-standards/email-standards#12]
/polls Here is option 1 'Option 2 goes here' "Option 3 in double quotes maybe"

**Comment by dylanatsmith** [comment]
Womp womp

**Comment by Malvoz** [comment]
It looks like the poll plugin didn't work. I'd just like to note that there's [now support](https://github.blog/2022-04-12-whats-new-in-github-discussions-organization-discussions-polls-and-more/) for [polls in GH discussions](https://github.com/email-markup-consortium/email-markup-consortium/discussions/new?category=polls).
