### ISSUE TITLE
Website planning

### ISSUE THREAD

**Issue by husseinalhammad** [email-standards/email-standards#16]
Assuming we have finalised the list of requirements for an MVP website (#5), it may be a good time to figure out how we're going to plan/manage the project (including discussing features we may want to include in the future).

Are we going to open a new repo and just using GitHub issues there for now? Are we going to use [GitHub Projects](https://github.com/orgs/email-standards/projects)? Something else?

**Comment by dylanatsmith** [comment]
I think a new repo with separate project management makes sense.

**Comment by husseinalhammad** [comment]
A new repo has been created: https://github.com/email-standards/website
